lambda@fileDelete and lambda@fileUpload
code-gambit/VT-lambdas pull request #28
Opened 2021-04-12 20:25 UTC by ayush0x00

# Description

Added lambdas for fileDelete and fileUpload

Fixes a part #20 

## Type of change

Please delete options that are not relevant.

- [x] Created new lambdas `@deleteFile` and `@uploadFile`

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-04-12 20:40 UTC, danishjamal104 requested changes
Rest everything is good

2021-04-12 20:40 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileDelete/package.json
> +  "author": "Lakshya Bansal <https://github.com/lakshya-20>",
update this.

2021-04-12 20:40 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileUpload/package.json
> +  "author": "Lakshya Bansal <https://github.com/lakshya-20>",
here also

2021-04-12 20:45 UTC, ayush0x00 commented on lambdas/file_access_patterns/lambda_for_fileDelete/package.json
> +  "author": "Lakshya Bansal <https://github.com/lakshya-20>",
Done

2021-04-12 20:45 UTC, ayush0x00 commented on lambdas/file_access_patterns/lambda_for_fileUpload/package.json
> +  "author": "Lakshya Bansal <https://github.com/lakshya-20>",
Done

2021-04-13 07:33 UTC, danishjamal104 approved these changes
LGTM

2021-04-13 19:38 UTC, lakshya-20 approved these changes

2021-04-13 19:39 UTC, merged