Added template for PR
code-gambit/VT-lambdas pull request #3
Opened 2021-04-05 21:53 UTC by ayush0x00

Fixes #2

2021-04-05 22:36 UTC, danishjamal104 requested changes
Also, you haven't mentioned anything regarding the title of the PR. Please address that also. Thanks.

2021-04-05 22:36 UTC, danishjamal104 commented on .github/pull_request_template.md
> +**Test Configuration**:
This repo is only for storing lambda files, hence no test configuration is required please remove this.

2021-04-05 22:36 UTC, danishjamal104 commented on .github/pull_request_template.md
> +- [ ] My changes generate no new warnings
No test cases hence remove this.

2021-04-05 22:36 UTC, danishjamal104 commented on .github/pull_request_template.md
> +- [ ] New and existing unit tests pass locally with my changes
remove this too, same as previous one

2021-04-05 22:36 UTC, danishjamal104 commented on .github/pull_request_template.md
> +## Type of change
Only possibility changes are update in previous lambdas or create a new one so remove the default checklist and add this
```md
- [ ] Update lambda @<name of lambda>
- [ ] Created new lambda @<name of lambda>
- [ ] Other 
```

2021-04-06 10:33 UTC, danishjamal104 commented
@ayush0x00 , you are making changes directly to the master. Not preferable at all.

2021-04-06 11:16 UTC, danishjamal104 approved these changes
LGTM

2021-04-06 11:17 UTC, danishjamal104 commented
@ayush0x00 , edit the title of PR to follow the convention.

2021-04-06 12:56 UTC, chhavituteja approved these changes

2021-04-06 12:57 UTC, chhavituteja approved these changes

2021-04-06 13:38 UTC, merged