Fixes #46: create-user modified to support post confirmation cognito flow
code-gambit/VT-lambdas pull request #49
Opened 2021-04-26 19:58 UTC by danishjamal104

fixes #46 

**Description**
Now, this lambda is automatically called when the user is signed up for a time, with the provided data.
And further it adds those data to dynamo db as `METADATA`.

2021-04-27 12:57 UTC, lakshya-20 commented
@ayush0x00 @danishjamal104  shall we push the output zip file into this repo?

2021-04-27 13:05 UTC, lakshya-20 requested changes
I think you have added this for testing purpose :)

2021-04-27 13:05 UTC, lakshya-20 commented on lambdas/user_access_patterns/lambda_for_createUser/index.js
> +  console.log(event)
Remove or comment this statement.

2021-04-28 06:09 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_createUser/index.js
> +  console.log(event)
it will be throwing the error, why comment on the export statement?

2021-04-28 06:17 UTC, danishjamal104 commented
> @ayush0x00 @danishjamal104 shall we push the output zip file into this repo?

not required, just make the release branch and make sure that release code is published onto lambda console.

2021-04-28 12:15 UTC, ayush0x00 commented on lambdas/user_access_patterns/lambda_for_createUser/index.js
> +  console.log(event)
Not export but console.log statement

2021-04-28 18:04 UTC, ayush0x00 approved these changes

2021-04-29 10:09 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_createUser/index.js
> +  console.log(event)
checkout now

2021-04-29 17:30 UTC, lakshya-20 approved these changes

2021-04-29 17:31 UTC, merged