lambda_for_findFileByName
code-gambit/VT-lambdas pull request #67
Opened 2021-05-23 12:35 UTC by lakshya-20

# Description

Implemented lambda to find a file by name

Fixes #66 

## Type of change

Please delete options that are not relevant.

- [ ] Updated lambda `@<name of the lambda>`
- [X] Created new lambda `@lambda_for_findFileByName`
- [ ] Other

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2021-05-23 21:02 UTC, danishjamal104 requested changes
Use KeyConditionExpression with beginning with function, so that we get all files matching the searchParams

2021-05-23 21:46 UTC, lakshya-20 commented
> Use KeyConditionExpression with beginning with function, so that we get all files matching the searchParams

Yes, it is there

2021-05-24 17:52 UTC, danishjamal104 commented
> > Use KeyConditionExpression with beginning with function, so that we get all files matching the searchParams
> 
> Yes, it is there

I can't see it, where comment inline.

2021-05-24 17:59 UTC, danishjamal104 approved these changes

2021-05-24 18:00 UTC, merged