Merging dev into master
code-gambit/VT-lambdas pull request #86
Opened 2021-06-06 22:16 UTC by ayush0x00

# Description

The dev branch is stable and currently ready to be released as v1.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Updated lambda `@<name of the lambda>`
- [ ] Created new lambda `@<name of the lambda>`
- [x] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-07 01:01 UTC, danishjamal104 requested changes
Please consider all the comments and changes requested. Since most of the lambdas are pretty stable and working fine, it's better we focus more on release. There are few points to be considered for this which are mentioned below:

1. **Document each lambda:** Add docstring on line 1 of each indes.js for each lambda. The docstring must contain the purpose of the lambda for example if it is used for API gateway then mention the endpoint it is triggered for or if it is used for Cognito add a stage at which it is called, or else just mention that this is a utility function. Refer [JDOC](https://jsdoc.app/) for documentation guide.
2. **Remove aw-sdk from package.json:** Since `aws-sdk` is by default included at runtime no need to add it release artifact, it will reduce the release size and also will be more maintainable.
3. **Update Swagger UI:** Make sure that each model and end point are updated on swagger before making a new release.

2021-06-07 01:01 UTC, danishjamal104 commented on Api/model.md
> +  "thumbnail": "<profile image url>: String"
`thumbnail` we are not allowing users to upload profile images, then why we still have it?

2021-06-07 01:01 UTC, danishjamal104 commented on Api/model.md
> +## File
Below is one of the file entries from the database, which has a significant difference from what is mentioned in the model.md. Sync this

```JSON
{
 "PK": "USER#42d-eca8-4891-b3a3-7bb5fffe60d2",
 "SK": "FILE#2021-05-31-20-32-21",
 "LS1_SK": "mongo",
 "size": 14354.766,
 "f_type": "Other",
 "hash": "QmcQ4YNMNBotPYJ1NxJy5bEsSYSG5tPXmY7DcuYVfCFau7",
 "default": "50ENge"
}
```

2021-06-07 01:01 UTC, danishjamal104 commented on README.md
> +
The list of lambdas implemented and their purpose is missing.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileDelete/package.json
> +    "aws-sdk": "^2.884.0"
remove this.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileDetails/package.json
> +        "aws-sdk": "^2.884.0"
remove this.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileList/package.json
> +        "aws-sdk": "^2.884.0"
remove this too.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileUpload/package.json
> +    "aws-sdk": "^2.884.0",
remove this too.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/setup.py
> +    body: message,
update this to add the `error` key also the function signature, to error as an argument.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/setup.py
> +'Chhavi Tuteja <https://github.com/chhavituteja>',
remove this.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/setup.py
> +    return response(200, event);
update this based on new function signature,

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_deleteURL/index.js
> +        return  response(200,undefined,"URL delete success");
this must have been resolved with issue #72, but it isn't. Please update this to return the entire URL object instead of the text response.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_deleteURL/package.json
> +        "aws-sdk": "^2.884.0"
this too.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_getHash/package.json
> +        "aws-sdk": "^2.884.0"
this too.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_updateURL/package.json
> +        "aws-sdk": "^2.884.0"
this too.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_urlList/index.js
> +            Limit:10,
move this to the environment variable. So that we can upscale and downscale it without modifying the code itself.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileList/index.js
> +            Limit:10,
move this to the environment variable. So that we can upscale and downscale it without modifying the code itself.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_urlList/package.json
> +        "aws-sdk": "^2.884.0"
remove this.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_createUser/index.js
> +    thumbnail: userAttr['custom:profile_image'],
we are not using this, hence I think it would be better if we avoid adding it to the database.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_getUser/index.js
> +
remove unnecessary empty lines `11 and 12`.

2021-06-07 01:01 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_createUser/package.json
> +    "aws-sdk": "^2.883.0"
remove this.

2021-06-07 01:05 UTC, danishjamal104 commented
Also @lakshya-20 and @ayush0x00 , don't add separate commits for minor changes. Instead what we can do is, make 2 commits first one resolving all the code changes and updates the setup.py, and the second commit consisting of adding documentation above each lambda.

2021-06-07 05:13 UTC, ayush0x00 commented
What is to be updated in setup.py?

2021-06-07 05:35 UTC, danishjamal104 commented
> What is to be updated in setup.py?

Take a look at inline comments I have mentioned it.

2021-06-07 16:40 UTC, danishjamal104 requested changes
@ayush0x00 , there are still few changes required please take a look.

2021-06-07 16:40 UTC, danishjamal104 commented on README.md
> +
update this, @ayush0x00

2021-06-07 16:40 UTC, danishjamal104 commented on lambdas/user_access_patterns/lambda_for_getUser/index.js
> +
still not removed

2021-06-07 16:40 UTC, danishjamal104 commented on lambdas/url_access_patterns/lambda_for_deleteURL/index.js
> +        return  response(200,undefined,res);
Correct this with `res.Attributes`.

2021-06-08 01:00 UTC, danishjamal104 approved these changes
Everything looks good.

2021-06-08 01:01 UTC, danishjamal104 commented
@lakshya-20, go ahead with the documentation part.

2021-06-08 11:36 UTC, danishjamal104 requested changes
I am not adding a comment on each lambda, the same thing is to need to be modified, please take look.

2021-06-08 11:36 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileDelete/index.js
> +* This lambda takes the userId and fileId and deletes the corresponding file, updating the storage_used for the user with the given userId and delete all the corresponding URLs for the deleted file.
avoid using long single-line sentences in the docstring, instead break the line at sufficient length to make the code concise and readable.

2021-06-08 11:36 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileDetails/index.js
> +* This lambda takes the userId and fileId and returns the file details corresponding to the given fileId.
same here

2021-06-08 11:36 UTC, danishjamal104 commented on lambdas/file_access_patterns/lambda_for_fileList/index.js
> +* This lambda returns the file uploaded by a specific user. It supports pagination, text-based search and time-series query.
here too

2021-06-08 11:38 UTC, lakshya-20 commented on lambdas/file_access_patterns/lambda_for_fileList/index.js
> +* This lambda returns the file uploaded by a specific user. It supports pagination, text-based search and time-series query.
Okay.

2021-06-08 14:19 UTC, danishjamal104 requested changes
missing Astrix, docstring has star/Astrix in each line. In many lambdas, there are lines which are not starting with `*`. PLease fix it @lakshya-20

2021-06-08 14:39 UTC, danishjamal104 approved these changes
Perfect we are good to go.

2021-06-08 14:40 UTC, merged